### ISSUE TITLE
Schedule // Polymer

### ISSUE THREAD

**Issue by NeisRosver** [GamesDoneQuick/sgdq17-layouts#5]
Made this work on a local server but there is a scheme for schedule and runners, cuz i can't make mine works on 

And the other issue when i got when i was on bower install is a polymer  inside the typehead, and i just delete it and then when i was installing itself ask for the required version 
```
"nodecg-typeahead-input": "NodeCGElements/nodecg-typeahead-input#polymer-2"
"nodecg-typeahead-input": "NodeCGElements/nodecg-typeahead-input",
```

**Comment by Lange** [comment]
Hi @NeisRosver,

There's a number of issues which have appeared in this repository over time, and this codebase is not maintained due to us already being on the next GDQ event. My advice is to wait until early February when we release `agdq18-layouts`.

Best,
Alex
