### ISSUE TITLE
Installing npm dependencies (dev: false)... failed!

### ISSUE THREAD

**Issue by b390** [GamesDoneQuick/sgdq17-layouts#8]
![capture](https://user-images.githubusercontent.com/34553328/34755892-4ad5a0dc-f5d8-11e7-801b-c78977883514.PNG)

ok so after trying several times on installing i always do get this >_< one error that gets on my nerv lol i have tryed deleting the files and reinstalling but still i do go get on the sgdq17-layouts and the agdq17-layouts 

any idea how to fix this ?
p.s : am running the newest version NodeCG 0.9.8 (Running on Node.js v9.3.0)

**Comment by Lange** [comment]
Hi @b390,

There's a number of issues which have appeared in this repository over time, and this codebase is not maintained due to us already being on the next GDQ event. My advice is to wait until early February when we release `agdq18-layouts`.

Best,
Alex
